spring:
  application:
    name: driver-service
  config:
    import: 'optional:configserver: '
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
#
#springdoc:
#  swagger-ui:
#    # Swagger UI 접속 URL
#    path: /swagger-ui.html
#  api-docs:
#    # OpenAPI JSON URL
#    path: /v3/api-docs

eureka:
  instance:
    prefer-ip-address: false
    hostname: 35.216.57.113

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://35.216.57.113:3150/eureka/
server:
  port: 8089
